apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uvyb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uvyb
    app.kubernetes.io/part-of: tkrw-pr712-0075-0065-app
  name: devfile-sample-uvyb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uvyb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uvyb
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-uvyb@sha256:66d98cbd7ff589defb5142fd1a962827d7f5e6f73f338d1e239077886e240940
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
